### ISSUE TITLE
Зміна оригінальної схеми при ініціалізації пакету

### ISSUE THREAD

**Issue by Leits** [openprocurement/openprocurement.schemas.dgf#2]
Схема не має змінювати у процесі роботи із нею. 

@Krokop 

https://github.com/openprocurement/openprocurement.schemas.dgf/blob/master/openprocurement/schemas/dgf/schemas_store.py#L189

```
diff --git a/openprocurement/schemas/dgf/schemas/04/1/2/2/schema_001.json b/openprocurement/schemas/dgf/schemas/04/1/2/2/schema_001.json
index b065c31..bb5e06b 100644
--- a/openprocurement/schemas/dgf/schemas/04/1/2/2/schema_001.json
+++ b/openprocurement/schemas/dgf/schemas/04/1/2/2/schema_001.json
@@ -1,8 +1,5 @@
 {
-    "$schema": "http://json-schema.org/draft-04/schema#",
-    "type": "object",
     "title": "Schema for buildings 04122 1",
-    "additionalProperties": false,
     "required": [
         "number_of_kitchen",
         "total_area",
@@ -11,19 +8,22 @@
     ],
     "properties": {
         "living_space": {
+            "minimum": 0,
             "type": "integer",
-            "title": "Житлова площа",
-            "minimum": 0
-        },
-        "number_of_kitchen": {
-            "$ref": "../schema_001.json#/properties/number_of_kitchen"
+            "title": "Житлова площа"
         },
         "number_of_rooms": {
             "$ref": "../schema_001.json#/properties/number_of_rooms"
         },
         "total_area": {
             "$ref": "../schema_001.json#/properties/total_area"
+        },
+        "number_of_kitchen": {
+            "$ref": "../schema_001.json#/properties/number_of_kitchen"
         }
     },
-    "id": "file:///Users/serbokryl/work/schemas_store/schemas_store/schemas/04/1/2/2/schema_001.json"
-}
+    "additionalProperties": false,
+    "$schema": "http://json-schema.org/draft-04/schema#",
+    "type": "object",
+    "id": "file:///data/path/path/path/openprocurement.auctions.dgf/src/openprocurement.schemas.dgf/openprocurement/schemas/dgf/schemas/04/1/2/2/schema_001.json"
+}
```

Participants: @myroslav, @kroman0, @gregyanchak

**Comment by Krokop** [comment]
Глобально нічого не змінюється, тільки оновлюється id, це потрібно для формування зв'язків між схемами.

**Comment by Leits** [comment]
Формування зв'язків між схемами можна задати відносних шляхом, який не буде змінюватися у процесі роботи. 
Зараз же у файли пакету вносяться зміни і він стає неоновлюваним. **Dirty**.

**Comment by Krokop** [comment]
Згідно документації по схемам [json-schema](http://json-schema.org/latest/json-schema-core.html#rfc.section.8.2), id повино бути 

> a valid URI-reference [RFC3986]

Якщо я правильно зрозумів, то ми не можемо використовувати відносні шляхи.

**Comment by Leits** [comment]
[valid URI-reference](https://tools.ietf.org/html/rfc3986#section-3.3)

**Comment by Krokop** [comment]
Можете навести приклад ?

**Comment by Leits** [comment]
При глибшому аналізі виявили жорстку зав'язку при валідації у пакеті на абсолютний шлях до схеми.

Для вирішення цієї проблеми рекомендуємо перейти на urn.
Як `urn:uuid:ee564b8a-7a87-4125-8c96-e9f123d6766f` з прикладу у [json-schema](http://json-schema.org/latest/json-schema-core.html#rfc.section.8.2)

**Comment by Leits** [comment]
Fixed https://github.com/openprocurement/openprocurement.schemas.dgf/commit/e1d208b7aba31d2f725f4c7da4812e4ccabe9c01
